# 配置服务端口号
server:
  port: 8501

spring:
  # 配置数据库连接信息
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # jdbc:mysql://[ip地址]:[端口号]/[table名称]?...
    url: jdbc:mysql://192.168.116.129:3306/db_codeqna?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root  # mysql登录用户名
    password: 1234  # mysql登录密码
  # Redis的相关配置
  data:
    redis:
      host: 192.168.116.129 # redis服务的ip地址
      port: 6379  # redis服务的端口号

# mybatis的配置
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*/*.xml